language: php

sudo: false

php:
- 5.5
- 5.6
- 7.0
- hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - vendor/

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - composer test --quiet
